### ISSUE TITLE
"Statistik" Page blocked

### ISSUE THREAD

**Issue by ZhuYufei990** [highmed/SmICSCore#1]
with http://myServer_IP:9787/Statistik the page just blocked.
![SmICSWebApp - Google Chrome Do, 01 04 21 10_46_28 (2)](https://user-images.githubusercontent.com/79518032/113273871-5bc50b80-92dd-11eb-8ac6-b23da0f7f7c4.png)
![SmICSWebApp - Google Chrome Di, 06 04 21 17_26_14 (2)](https://user-images.githubusercontent.com/79518032/113736457-675d6b80-96fd-11eb-8ed8-039b95693144.png)

**Comment by wulffant** [comment]
@yussefal @biermapa is this now solved in the new version?

**Comment by yussefal** [comment]
Yes, this Issue has been solved in the new version!

**Comment by yussefal** [comment]
> @yussefal @biermapa is this now solved in the new version?

Yes, this Issue has been solved in the new version!
