### ISSUE TITLE
Optische Differenzierung Daten allgemeiner Natur und Daten aus meinem Krankenhaus o.ä.

### ISSUE THREAD

**Issue by Martin-Wiesenfeldt** [highmed/SmICSCore#10]
Wenn ich das richtig verstehe, beziehen sich bei der Statistik ersten beiden Buttons auf die Zahlen vom RKI, die anderen drei auf den eigenen Datenbestand. Das sollte irgendwie differenziert werden (jeweils Box drum, vertikaler Trennstrich, andere Buttonfarbe...).

**Comment by wulffant** [comment]
@yussefal Bitte erste Ideen zur Umsetzung überlegen, mit Martin absprechen, mit mir absprechen.

**Comment by yussefal** [comment]
> 
> 
> @yussefal Bitte erste Ideen zur Umsetzung überlegen, mit Martin absprechen, mit mir absprechen.

Eine Idee zur Umsetzung wurde nach der Vorstellung übernommen.
