### ISSUE TITLE
Offene Fragen Visualisierung

### ISSUE THREAD

**Issue by wulffant** [highmed/SmICSCore#111]
Icons mit oder ohne Langname
Workflow Kontaktnetzwerk <-> Patient History
Moving avg in epi curve?

**Comment by wulffant** [comment]
Klärt Sarah im nöchsten Termin mit Claas

**Comment by SarBall** [comment]
Antworten zu den Fragen aus Hannover: 

•	Icon mit oder ohne Langname (Bild kommt)
        **-> Icons hier bitte mit Langnamen** 
•	Workflow: Erst Kontaktnetzwerk und dann Patientenhistorie oder schaut man sich 
        erst die Historie an und möchte dann zu einem spezifischen Patienten das 
        Kontaktnetzwerk betrachten?
       **-> Zuerst kommt die Patientenhistorie und das Kontaktnetzwerk (wird im Alltag 
       nicht wirklich benutzt)** 
•	Moving Average über 28 bzw 7 Tage als zusätzliche Kurve in der Epidemiologischen 
        Kurve?
        **->Perfekt wäre wenn es hier aus wählbar wäre. Kann man hier eine Kurve 
        auswählen? Nicht zu viele Kurven wäre gut.**
