### ISSUE TITLE
Diagnose Angabe

### ISSUE THREAD

**Issue by SarBall** [highmed/SmICSCore#117]
Diagnose Angabe zB: Fall SARS-CoV-2 oder COVID oder
o	die Fälle, die als infektiöse SARS-CoV Fälle geführt sind-> Hier nochmal differenzieren (Absprache mit Tom und Antje/ Pascal) 
o	Die Ansicht bezieht sich auf die Laborbefunde

**Comment by biermapa** [comment]
Fehlende Daten zur Diagnose, daher aktuell nicht umsetzbar
