### ISSUE TITLE
Allgemein

### ISSUE THREAD

**Issue by SarBall** [highmed/SmICSCore#118]
- Genaue Lokalisation des Patienten-> Liegt dieser auf ein Bereich der Infektionsstation? Hier wird nochmal Unterschieden: 
o	Anzahl der Intensivbetten:  Covidpatienten der als infektiöse Covidpatienten versorgt wird; liegt hier in der Infektionsstation
o	Oder ein Patient der auf der Intensivstation invasiv beatmet wird der für einen langen Zeitraum Genesene sind aber nicht mehr infektiös geführt werden. 
o	Für spätere Entwicklung des SmICS. Genauere Lokalisation sind zurzeit nicht bekannt (Antje/ Pascal)

**Comment by biermapa** [comment]
Daten nicht vorhanden. Eventuell Codex+ oder späteres Projekt.
