### ISSUE TITLE
jan instead of Sun

### ISSUE THREAD

**Issue by dagmarkrefting** [highmed/SmICSCore#13]
In the timeline (Fallzahlen und Epidemiologische Kurve) sunday appears as "Jan"
Anyhow, when the figure title are in German, probably the weeknames should also appear in German?

![Screenshot from 2021-04-13 18-14-40](https://user-images.githubusercontent.com/10370998/114585722-3bedfa00-9c84-11eb-9220-add29fac3385.png)

**Comment by wulffant** [comment]
Thanks for the comment, we will redesign the entire view until the next release in July 
@biermapa

**Comment by wulffant** [comment]
- Ansicht wurde aktualisiert 
- Nennung des Monats ist so zur Orientierung vorgesehen
