### ISSUE TITLE
SmICSVisualisierung: failed by "npm install / run build"

### ISSUE THREAD

**Issue by ZhuYufei990** [highmed/SmICSCore#14]
Update by Version 0.9.0:
OS: Ubuntu 20.04
npm: v14, installed by nvm, just like in ReadME

First test all npm commands (install, run build, run server)  in the project, if they don't work locally, also can't work in docker container.

- npm install : if failed with node-sass, then try `npm install --unsafe-perm node-sass` to install it seperately, then run `npm install` again.  If it finished with some vulnerabilities (8 or 424), just fine. Don't try any `npm audit fix` with or without  ` --force` like suggested in the log output, it solves no problems but brings more. 

- npm run build:  if it exits with non-zero code including some Errors, don't worry. The important thing is that the folder build and its subfolders and .js files & co. in them were generated. If so (in our case), then try `npm run server` and no error anymore, test in the browser, everything is fine! 

----------- Two optinal work arounds that work by us ----------------------------
 
Work around 1 with docker container:
If the npm commands work locally, but failed in docker. Then first run "npm install" and "npm run build" locally, comment the two lines in Dockerfile for them, then build the docker container and start it, it works!

Work around 2 to keep npm commands inside docker container:
- "npm install" failed in docker container because of network access (error message like downloading some package, but failed by timeout),  try `docker build -t smicsvisualisierung --netwok host . ` to give the the container right network access.

- "npm run build" exits with non-zero code so the docker build process also exits, change that line in Dockerfile with  `RUN npm run build; exit 0 `  to skip the error and finish the process. 

-----------------Till Version 0.8.0-------------------------
OS: Debian 10.9
node: 14.16.0

[2021-04-07T09_58_00_326Z-debug.log](https://github.com/highmed/SmICSVisualisierung/files/6271104/2021-04-07T09_58_00_326Z-debug.log)
[2021-04-07T09_58_00_490Z-debug.log](https://github.com/highmed/SmICSVisualisierung/files/6271105/2021-04-07T09_58_00_490Z-debug.log)

**Comment by wulffant** [comment]
Tom is working on a bug fix.
Meeting Tom & Pascal will take place after authentication is implemented

**Comment by wulffant** [comment]
Alan testet nochmal und meldet es an Pascal zurück

**Comment by yussefal** [comment]
Lokal hat funktioniert, aber auf dem Server nicht, deshalb muss ich es nochmal testen und das Ergebnis mit @biermapa  besprechen

**Comment by wulffant** [comment]
In Hannover mit Ubunutu 20.04 -> keine Probleme
