### ISSUE TITLE
Visualisierung readme: private git-Repo in ReadME

### ISSUE THREAD

**Issue by ZhuYufei990** [highmed/SmICSCore#15]
It is including the private Git Repository from Darmstadt in README.

**Comment by wulffant** [comment]
needs more description, please explain @ZhuYufei990

**Comment by wulffant** [comment]
Update der readme Visualisierungsdatei - wird im nächsten Visualisierungsmeeting besprochen.

**Comment by wulffant** [comment]
Am Mittwoch (Visu-Meeting) an Tom weitergegeben, Link wird entfernt.

**Comment by wulffant** [comment]
@ZhuYufei990 checkt ob es erledigt ist und closed dann. Ansonsten geben wir es an Tom weiter.

**Comment by ZhuYufei990** [comment]
"git clone git@gitlab.gcc.informatik.tu-darmstadt.de:highmed/infectioncontrolsystem2.git" still in ReadME of Visuralisierung  project.

**Comment by wulffant** [comment]
geändert
