### ISSUE TITLE
Design Vorschläge

### ISSUE THREAD

**Issue by wulffant** [highmed/SmICSCore#18]
Weitere Vorschläge seitens unserer Design-Expertin:

- [x] -	Kontaktinformationen im Footer ergänzen
- [x] -	Links prüfen
- [x] -	Links hinter den Logos hinterlegen, die zu den jeweiligen Projektseiten führen
- [x] -	ggf. eine Logo für das SMICS entwickeln
- [x] -	alles Logos auf das gleiche Format bringen und in den Footer verschieben
- [x] -	BMBF-Logo erweitern um „gefördert vom“

_Originally posted by @Martin-Wiesenfeldt in https://github.com/highmed/SmICSCore/issues/5#issuecomment-830084138_

**Comment by wulffant** [comment]
@biermapa @Kuri99 Könntet ihr mal prüfen, was davon schon umgesetzt wurde und dann hier entsprechend abhaken? Danke

**Comment by Kuri99** [comment]
@wulffant  Welche Kontaktinformationen sollen den hinterlegt werden? Von wem?

**Comment by wulffant** [comment]
"Kontaktinformationen im Footer ergänzen" und "BMBF-Logo erweitern um „gefördert vom" werden beim nächsten merge eingepflegt.

**Comment by wulffant** [comment]
@wulffant
