### ISSUE TITLE
can not get right response from AQL Queries

### ISSUE THREAD

**Issue by ZhuYufei990** [highmed/SmICSCore#2]
with Ehr Base Server we got 400 by some AQL Queries, oder 200 but empty response body, so the frontend got 500 and showed nothing. With Better Server it should work better.

**Comment by wulffant** [comment]
Wie ist der Stand bzgl AQL-Updates in EHRbase?
@biermapa @birgerhaarbrandt 

Letzter Stand: 23.04. EXISTS funktioniert

**Comment by ZhuYufei990** [comment]
next Problem: Ehr Base Server doesn't want 'Fall-Kennung' in AQL Query for PatientAdmission & PatientDischarge:

and c/context/other_context[at0001]/items[at0003 **,'Fall-Kennung'** ]/value/value = '00000005'

**Comment by wulffant** [comment]
@biermapa  will modify 2 AQLs with Fall-Kennung
