### ISSUE TITLE
Fix minor bugs/changes in the RKI algorithm interface

### ISSUE THREAD

**Issue by wulffant** [highmed/SmICSCore#22]
- [x] improved naming of output variables for visualization team,
- [x] using of dynamic path for saving and retrieving of json files with input/output variables,
- [x] catching variational phrases for negative/positive/not detected test result in the AQL,

**Comment by PaulWaldstein** [comment]
- [x] catching variational phrases for negative/positive/not detected test result in the AQL,

**Comment by wulffant** [comment]
temporary saving of algorithm results for faster local retrieving for visualization -> in json #68
