### ISSUE TITLE
Edit Data representation in Statistikmodul

### ISSUE THREAD

**Issue by wulffant** [highmed/SmICSCore#23]
Die Daten sind nicht gut lesbar, da die Dezimaltrennzeichen bei den Zahlen fehlt.

![Dashboard](https://user-images.githubusercontent.com/80678828/116985679-1c6b4f80-accd-11eb-81dc-6949a1d7a2ff.png)

**Comment by yussefal** [comment]
> 
> 
> Die Daten sind nicht gut lesbar, da die Dezimaltrennzeichen bei den Zahlen fehlt.
> 
> ![Dashboard](https://user-images.githubusercontent.com/80678828/116985679-1c6b4f80-accd-11eb-81dc-6949a1d7a2ff.png)

@wulffant hier ist eine kurze Beschreibung.

**Comment by yussefal** [comment]
Die Daten wurden im Feature angepasst angepasst und können in Devlope gemerged werden!
