### ISSUE TITLE
SmICS Ehrbase Anbindung 

### ISSUE THREAD

**Issue by wulffant** [highmed/SmICSCore#28]
SmICS EHRbase Anbindung testen

**Comment by ZhuYufei990** [comment]
Aktuelle Bug Issue liegt in Ehrbase Projekt:

https://github.com/ehrbase/ehrbase/issues/507

**Comment by wulffant** [comment]
Christian hat Fehler in EHRbase behoben und zur Verfügung gestellt.
Leider immer noch Fehler vorhanden (jetzt sogar mehr Fehler?)
Pascal hat Christian zurückgemeldet

**Comment by wulffant** [comment]
Bisher noch keine Rückmeldung von EHRbase

**Comment by wulffant** [comment]
3 Queries funktionieren noch nicht
-> Birger reviewed, ggf Fehler bei EHRbase Installation

**Comment by wulffant** [comment]
1 Query für EpiCurve noch offen
