### ISSUE TITLE
Spell mistakes in the both postman_collection files in /TestData

### ISSUE THREAD

**Issue by ZhuYufei990** [highmed/SmICSCore#3]
**SmICS_TestDataCollection.postman_collection:**
for Patient 1-16, request body in Stat. Versorgungsfall, code_string for "Organisationsschlüssel" were "100" or "500", but the server wants "0100" / "0500". Ehrbase Server can that accept, but Better not.

**SmICS_AQLCollection.postman_collection:**
* in EpiCurve should first run EpiCurve copy, then PatientLocation, not like the order in Postman
* in LabData, request body missed ">" for ehrID

**Comment by wulffant** [comment]
Please close issue if it has been resolved in the current version @biermapa

**Comment by wulffant** [comment]
@Kuri99 solved these errors
@biermapa needs to merge
