### ISSUE TITLE
Kontakterfassung klinisches Personal (Prototyp)

### ISSUE THREAD

**Issue by wulffant** [highmed/SmICSCore#30]
Formulare einpflegen nach den Templates
@Kuri99 bitte hier einmal die Links zu den verwendeten Templates einfügen

**Comment by Kuri99** [comment]
Formulare angepasst. Tests fehlen noch.

**Comment by Kuri99** [comment]
Erstes Formular lässt sich ohne Problme abspeichern. Die beiden anderen werden angepasst.

**Comment by wulffant** [comment]
Absprache mit Antje bzgl. Formular/Template (mandatory/optional)

**Comment by Kuri99** [comment]
Links zu den Templates:

- Bericht zur Kontaktverfolgung (http://88.198.146.13/ckm/templates/1246.169.794)
- Personendaten (http://88.198.146.13/ckm/templates/1246.169.1168)
- Personeninformation zur Infektionskontrolle (http://88.198.146.13/ckm/templates/1246.169.1082)

**Comment by Kuri99** [comment]
Die beiden anderen Formulare sind jetzt angepasst und müssen auf Better getestet werden.

**Comment by Kuri99** [comment]
Alle Formulare lassen sich jetzt abspeichern.

Next: Tests für die dazugehörigen Schnittstellen und Connections

**Comment by Kuri99** [comment]
Alle Test im SmICS haben ein Konvertierungsproblem beim Abgleichen der Daten. Wir suchen noch nach einer Lösung.

**Comment by wulffant** [comment]
Prototyp
Hinweisfeld personalrechtl/datenschutzrechtl
Namen anpassen

**Comment by wulffant** [comment]
Überschrift: Formular zur Erfassung von Kontakten des klinischen Personals (Prototyp)

Text: Das SmICS stellt Formulare bereit, über die die Dokumentation von infektiologisch-relevanten Kontakten des klinischen Personals zu Patient:innen getestet werden kann. Die Eingaben zur Dauer des Kontakts, der getragenen Schutzkleidung und weiteren Felder, werden auf dem angebundenen standardisierten Datenrepositorium gespeichert und sind von dort aus für weitere Abfragen nutzbar. Kontaktieren Sie dafür bitte Ihr medizinischen Datenintegrationszentrum.

Bitte beachten Sie: Es handelt es sich hier ausdrücklich um einen Prototyp, mit dem die grundsätzliche Funktionalität und der potentielle Mehrwert dieser Erfassungsart evaluiert werden kann. Bevor Sie Echtdaten eingeben, halten Sie Rücksprache mit Ihrem Datenschutz, den personalrechtlichen Veranwortlichen und der IT-Abteilung, ob dieser Weg der Kontaktnachverfolgung für die mitarbeitenden Personen rechtlich gesichert genutzt werden darf.

**Comment by Kuri99** [comment]
Seite angepasst. Merge wird für nächste Woche vorbereitet.
