### ISSUE TITLE
FHIR Bridge for SmICS

### ISSUE THREAD

**Issue by wulffant** [highmed/SmICSCore#34]

**Comment by ZhuYufei990** [comment]
Zustand am ~~21.05.2021,10:00~~
 ~~28.05.2021, 11:00~~
~~04.06.2021, 12:00~~
~~25.06.2021, 10:30~~
~~23.07.2021, 10:15~~
~~06.08.2021, 10:00~~
13.08.2021, 10:00

- Impfstatus -> done
- Pateintenaufenthalt -> done
- Stationär Versorgungsfall -> done
- Symptom -> done
- Virologischer Befund -> done
- Mikrobiologischer Befund -> zuerst nicht von B-FAST SmICS gebraucht

**Comment by wulffant** [comment]
- Norman hat openEHR SDK issue angelegt (Impfstatus) und wartet auf fix

**Comment by wulffant** [comment]
- FHIR Bridge Mappings -> Ehrbase NUM issue 128  
- Soweit fertiggestellt
- Beachten: Canon. Links
