### ISSUE TITLE
Übergeordnete Task: R-Algorithmus RKI einbinden

### ISSUE THREAD

**Issue by wulffant** [highmed/SmICSCore#36]
Einbindung des RKI R-Algorithmus zur Detektion von Clustern/Ausbrüchen 

- [x] Variante für virologische Erreger
- [x] Variante für mikrobiologische Erreger
- [x]  kurze Doku erstellen für end. Niveau, Ausbruchswahrscheinlichkeit, Obergrenze
- [x] ggf. Einstellen der Look-Back-Variable durch user ermöglichen (bspw. in Wochen, z.B. 1,2,4,8)
- [x] Catch für Datumsangaben bzgl Look-back einbauen
- [x] Fehlermeldung

additional issues related to this issue: #19 and #22

**Comment by wulffant** [comment]
additional issues related to this issue: #19 and #22

**Comment by wulffant** [comment]
- [ ] kurze Doku erstellen für end. Niveau, Ausbruchswahrscheinlichkeit, Obergrenze

**Comment by wulffant** [comment]
**abhängig von AQL-Bug in #22**

**Comment by PaulWaldstein** [comment]
Kurze Doku für end. Niveau, Ausbruchswahrscheinlichkeit und Obergrenze:

[https://owncloud.gwdg.de/remote.php/webdav/B-Fast/Aufgabenbereich%20%22Algorithmen%22/Bestimmung_der_Outputgroessen_im_RKI_Algorithmus.pdf](url)

**Comment by wulffant** [comment]
Look-back-Variable und Catch: Paul schreibt Tom bzgl. Visualisierungsanforderungen (Warnhinweis + Eingabe/Auswahlfeld)

**Comment by PaulWaldstein** [comment]
Bei der Iteration zur Bestimmung der Ausbruchswahrscheinlichkeit können sehr selten Fälle/Parameterzusammensetzungen auftreten, bei denen der Algorithmus mit einem Stop-Switch und einer Benachrichtigung abbricht. Künftig wird Information über solche Fälle mit einer zusätzlich definierten Outputvariablen an die C#-Schnittstelle übergeben.

**Comment by wulffant** [comment]
Fehlermeldung, wenn Daten bei 1-3 Wochen Lookback nicht ausreichen für ein sicheres Ergebnis / es zu einem Fehler bei der Ausführng des Algorithmus kommt

**Comment by wulffant** [comment]
- Kontakt mit Ann Christin Vietor (RKI) aufgenommen bzgl. Bugs (Mail 29.7.)
- Paul versucht die FEhlbermeldung am 30.07. einzubauen.

**Comment by PaulWaldstein** [comment]
Als Fehlermeldung wurde in der Json-Datei mit Ergebnissen für die Datenbank und für die Visualisierung ein zusätzliches Attribut ''Algorithmusergebnis enthaelt keine null-Werte'' hinzugefügt. Wenn der Algorithmus in einer Iteration null-Werte liefert, ist ''Algorithmusergebnis enthaelt keine null-Werte'' gleich false.
