### ISSUE TITLE
Weiterentwicklung der Statistikmodule

### ISSUE THREAD

**Issue by yussefal** [highmed/SmICSCore#37]
**Ziel:** Bessere Repräsentation der Daten mittels Chart. 

**Stand:** Die Daten zusammenführen, um sie in Charts einzubinden. Desweiteren aus dem Testbeispiel unten zu entnehmen.

**Lizenzen:** Es werden folgende Charts,  Line Chart,  Bar Chart und Pie Chart aus dem [Repository ](https://github.com/mariusmuntean/ChartJs.Blazor) verwendet, welches unter dem MIT License läuft.

![Test1](https://user-images.githubusercontent.com/80678828/119119510-8a34ac80-ba2b-11eb-960c-4fb751446f99.png)

**Comment by wulffant** [comment]
Bitte finalisieren, dann zunächst keine neuen Funktionen und Schnittstellen. 
Fokus nächste Phase: Einarbeitung Feedback Anwender:innen

**Comment by yussefal** [comment]
**Stand:**  EHR Daten in Charts eingebunden. 
**TODO:** Code Review mit @biermapa

**Comment by yussefal** [comment]
**Stand**: Review mit @biermapa durchgeführt.
**TODO** Änderungen bzw. Verbesserungen vornehmen, um es beim nächsten Merge Termin nächste Woche zu mergen.

**Comment by yussefal** [comment]
- [x] Sowohl EHR Daten als auch RKI Daten wurden eingebunden. 
- [x] CronJob erstellen, um RKI Daten zu aktualisieren.

**Comment by yussefal** [comment]
Die Weiterentwicklung ist abgeschlossen. Es muss nur noch getestet werden!

**Comment by yussefal** [comment]
Die Änderungen sind in cosurv_develop gemerged worden
