### ISSUE TITLE
Dokumentation der Fehler bei SmICS Core Installation/Docker

### ISSUE THREAD

**Issue by wulffant** [highmed/SmICSCore#38]
Ubuntu related issues with Docker-support? Please document here.

Extension and refinement of repositories installation and execution manual.

**Comment by wulffant** [comment]
Termin nächste Woche, dann wird readme aus SmICS Core angepasst
Hier bitte die Änderungen kurz dokumentieren

**Comment by PaulWaldstein** [comment]
Beim Termin wurden folgende Punkte als Ergänzungen vorgeschlagen:

- Nummerierung der Installationsschritte,
- Unterteilung des Docker-Aufrufs in zwei Gruppen, da der Befehl ''network create'' nur einmal erforderlich ist,
- Hinweis auf wechseln ins Visualisierungsverzeichnis nachdem der Docker gestartet ist,
- starten der Kommunikation zwischen dem SmICSCore- und dem SmICSVisualisierungsmodul,
- ein vorausgehender Abschnitt zur Erläuterung einer Vorgehensweise bei Updates,

In der readme wurde noch nichts geändert, weil die Punkte beim Weekly Meeting ggf. erstmal besprochen werden sollen.

**Comment by wulffant** [comment]
Es folgt ein Termin zwischen Pascal und Alan bzgl. Update (siehe dazu #45). Die Ergebnisse werden ebenfalls in die Installationsanweisung aufgenommen. 

Nächster Schritt: Vorschlag für eine modifizierte readme/Installationsanleitung bis zum nächsten Weekly aufsetzen.

**Comment by wulffant** [comment]
Alan hat Vorschlag für readme geschickt, Pascal hat Feedback am 18/06/21 gegeben und aktualisiert readme.
