### ISSUE TITLE
RollOut Checkliste für Standorte

### ISSUE THREAD

**Issue by wulffant** [highmed/SmICSCore#39]

**Comment by wulffant** [comment]
In Arbeit durch Sylvia und @Martin-Wiesenfeldt. 
Bitte #47 in die Checkliste aufnehmen (Zugriff von SmICS nach außen).

**Comment by wulffant** [comment]
Fragebogen zur Evaluation des Co-Surv-SmICS wird erstellt

**Comment by sylvializmirandah** [comment]
Design of software evaluation questionnaire in progress based on software quality characteristics as outlined in ISO 25010

**Comment by sylvializmirandah** [comment]
In einem ersten Schritt wird es einen Bewertungsbogen für die SmICS Tests geben. Im zweiten Schritt wird eine Umfrage zur Evaluation des SmICS erstellt (Rollout).

Update 15. Juli:    
Entwurf eines Co-Surv-SmICS Software Test Fragebogens (Version für Techniker) wurde erstellt und am 9.7. an Martin Wiesenfeldt und Sabine Rey zur Durchsicht geschickt. Die finale Version wird auch an Antje Wulff und Pascal Biermann geschickt, bevor sie veröffentlicht wird. Möglicherweise Nutzung von LimeSurvey zur digitalen Bearbeitung und Auswertung der Fragebögen.

**Comment by sylvializmirandah** [comment]
Update 17. August:
- Erster Entwurf des SmICS Test Fragebogens für Techniker wurde zur Durchsicht an Pascal und Antje geschickt
- Fragebogen zur Bewertung der Benutzerfreundlichkeit und Gebrauchstauglichkeit des Co-Surv-SmICS für Anwender/Hygieniker. Termin zur Abstimmung der SmICS Usability Fragebögen mit Michael Behnke (Charité Berlin), Michael Storck (Universität Münster) und Sabine Rey am 3. September. Herr Behnke und Herr Storck haben schonmal eine SUS (Software Usability Scale) – Kurzumfrage zur Benutzerfreundlichkeit des HiGHmed SmICS - gemacht und Michael Storck hatte noch gute Ideen für weitere Add-On Fragen (SUS Health Fragen). Hier sollen die KPIs, die der Use Case Infection Control definiert hat, über einen Fragebogen erfasst werden.
Pascal: Wir können den gleichen Test für B-FAST und HiGHmed zwar fahren, allerdings gibt es in HiGHmed komplett andere Ansichten, deshalb muss es zwei unterschiedliche Abfragen geben (Co-Surv-SmICS und Mibi-SmICS).

**Comment by sylvializmirandah** [comment]
Meeting mit dem Universitätsklinikum Augsburg (UKA) am 17.09. und der Universitätsmedizin Greifswald (UMGW) am 28.09., um das Co-Surv-SmICS vorzustellen und Möglichkeiten der Zusammenarbeit bzgl. FHIR Strecke zu eruieren. Diese beiden FHIR-Standorte haben nach der Antragsstellung für B-FAST keine weitergehenden Informationen erhalten und haben um einen Überblick über die Projektinhalte, Infos zum Datensatz sowie zur Implementierung des SmICS Systems (z.B. benötigte Schnittstellen) gebeten.

**Comment by wulffant** [comment]
- [x] Link einfügen zur Checkliste, dann schließen @sylvializmirandah

**Comment by sylvializmirandah** [comment]
https://owncloud.gwdg.de/index.php/apps/files/?dir=/B-FAST/60_Work_Packages/03_WP_3/Co-Surv-SmICS/Intern/AP3.9%20SmICS%20Rollout/Dokumente/Co-Surv-SmICS%20Spezifikationen%20Rollout&fileid=1454705764
