### ISSUE TITLE
Zusammenstellung und Ergänzung der fachlichen Dokumentation

### ISSUE THREAD

**Issue by wulffant** [highmed/SmICSCore#42]
Durch Sylvia

**Comment by wulffant** [comment]
Absprache am 01.06. mit Sylvia 

Benutzerhandbuch wird angepasst
Stand der Dokumente zu Datenschutz/Ethik wird nachgefragt
Checkliste für das Rollout wird erstellt

**Comment by wulffant** [comment]
@wulffant hat das modifizeirte Handbuch bekommen, Feedback kommt

**Comment by sylvializmirandah** [comment]
Status update: June 24th

**User manual**
User manual of Co-Surv-SmICS V0.8 (Test): editing (proofreading, correction, updating screenshots for statistics module) completed on June 22nd
Alan to incorporate amendments in his branch

**Software Rollout and Deployment Checklists**
Software evaluation questionnaire in progress 

**Data security concept/ethical approval** 
Göttingen to provide conceptual framework and coordinate with other B-FAST stakeholders from WP1 (Uniklinik Köln, MRI-TUM, Universitätsklinikum Halle-Saale & RKI)
Legal opinion can be obtained from TMF (Technologie- und Methodenplattform für die vernetzte medizinische Forschung e.V.)
Sabine Rey will look into regulatory requirements in July 2021

**Comment by sylvializmirandah** [comment]
Update 15. Juli: 

- Kurzanleitung des Co-Surv-SmICS (zwei DIN A4 Seiten) wurde erstellt und in den internen ownCloud Co-Surv-SmICS Ordner (Rollout) abgelegt. 
- Benutzerhandbuch wurde überarbeitet und in den internen ownCloud Co-Surv-SmICS Ordner (Rollout) abgelegt. 
- Entwurf eines Co-Surv-SmICS Software Test Fragebogens (Version für Techniker) wurde erstellt und am 9.7. an Martin Wiesenfeldt und Sabine Rey zur Durchsicht geschickt. Möglicherweise Nutzung von LimeSurvey zur digitalen Bearbeitung und Auswertung der Fragebögen.

**Comment by wulffant** [comment]
Kurzvideo hochgeladen: https://www.youtube.com/watch?v=-OyovVkhrn4 
@sylvializmirandah schickt Antje die Kurzanleitung, dann hochladen in den öffentl. Bereich
Antje und Pascal bekommen Software Test Fragebogen nach dem Review durch Sabine/Martin zur Durchsicht

**Comment by sylvializmirandah** [comment]
Kurzanleitung des Co-Surv-SmICS V. 0.8 wurde an Antje Wulff geschickt

**Comment by sylvializmirandah** [comment]
Update 23. Juli: 

- Kurzanleitung wurde in den öffentlichen ownCloud Ordner in "Dokumente" hochgeladen
- Kurzvideo mit Einführung in das SmICS wurde in den öffentlichen ownCloud Ordner in "Medien" hochgeladen
- Tabelle mit Informationen zur Datenbanknutzung aller B-FAST Projektpartner wird erstellt. Es wurde von einigen Koorperationspartnern der Wunsch nach einer Zeitschiene und einer Einbindung in die bestehende Kommunikation des B-FAST Projekts geäußert (z.B. von den Standorten Augsburg, Greifswald, Marburg/Gießen).
- Software Test Fragebogen für Techniker wird an Antje und Pascal verschickt sobald @sylvializmirandah eine Rückmeldung von Sabine Rey bekommen hat.
- HiGHmed Konferenz Takeaway: Fragebogen für das Feedback der Anwender soll sehr einfach gehalten werden.

**Comment by Martin-Wiesenfeldt** [comment]
Paul ergänzt eine Beschreibung des "Bene"-Algorithmus für das Handbuch

**Comment by wulffant** [comment]
Neues Benutzerhandbuch für V1.0 bereitgestellt.
