### ISSUE TITLE
Administration und Monitoring Köln-Server SmICS und EHRbase

### ISSUE THREAD

**Issue by wulffant** [highmed/SmICSCore#45]

**Comment by yussefal** [comment]
ToDo: 

1. Testdaten hinzufügen bzw. aktualisieren
2. SmICS Core aktualisieren

**Comment by wulffant** [comment]
Dokumentation über Update-Verfahren/Prozess in Installationsanweisung (readme) ergänzen, siehe auch #38

**Comment by yussefal** [comment]
Am 10.06 fand ein Termin mit @biermapa statt, wo wir gemeinsam die Installation von SmICS Core und EHRbase auf Köln-Server fortgesetzt bzw. ergänzt haben.

Am 14.06 habe ich EHRbase und SmICS bei mir lokal aufgesetzt, um später das Visualisierungsteam so gut wie möglich zu unterstützen und um die Installationsanweisung zu überprüfen #38 .

**Comment by wulffant** [comment]
Email an Köln geschickt, ab jetzt normaler Monitoring + Adminprozess gestartet.
