### ISSUE TITLE
RKI-Statistikmodul: Ankündigung von Updates

### ISSUE THREAD

**Issue by wulffant** [highmed/SmICSCore#46]
Klären, ob es die Möglichkeit gibt, über anstehende Updates an der RKI-Dashboard-Schnittstelle informiert zu werden.

**Comment by Martin-Wiesenfeldt** [comment]
Antwort des RKI: So eine Mailingliste gibt es leider nicht.
Es müssen also andere Mechanismen verwendet werden.

**Comment by Martin-Wiesenfeldt** [comment]
Sehr geehrter Herr Dr. Wiesenfeldt,

eine Mailingliste dafür gibt es leider nicht.

Mit freundlichen Grüßen
i.A.
Viviane Bremer

****************************************** 
 Dr. med. Viviane Bremer MPH
 Fachgebietsleiterin
 HIV/AIDS und andere sexuell oder durch
 Blut übertragbare Infektionen
 Robert Koch-Institut
 Seestrasse 10
 13353 Berlin
 Tel:  +49-30-18754-3487
 Fax: +49-30-18754-3533
 www.rki.de 
 

----  

als Antwort auf folgende Mail:

Guten Tag, 
im Rahmen des vom BMBF geförderten B-FAST- Programms (https://www.umg.eu/forschung/corona-forschung/num/b-fast/) entwickeln wir zusammen mit der MHH Hannover ein Programmtool für Krankenhaushygieniker zur Nachverfolgung von COVID-19-Infektionen innerhalb der Krankenhäuser. Dies soll im dann als Teil des NUM-Knotens (https://www.netzwerk-universitaetsmedizin.de/) allen teilnehmenden Universitätskliniken (und darüber hinaus) zur Verfügung gestellt werden.
Ein Teil der integrierten Programmfunktionalität ist die Darstellung der aktuellen allgemeinen Infektionssituation, wobei wir für diesen Zweck die Daten von Ihnen über API’s herunterladen.
Letzte Woche haben wir festgestellt, dass eine dieser Dateien das Format leicht geändert hatte. Die Anpassung war, nachdem wir dies festgestellt hatten, kein Problem. Allerdings haben  wir uns gefragt, ob wir für den nun bevorstehenden Produktiveinsatz in den Krankenhäusern solche Änderungen möglichst bereits im Vorfeld erfahren könnten und so die zu erledigenden Änderungen auch vorab bei uns durchführen könnten, um die Downtimes zu minimieren.
Gibt es da z.B. eine Mailingliste, in die man sich eintragen könnte, über die solche Änderungen kommuniziert werden? Oder einen anderen Prozess?
In diesem Fall fanden sich die Änderungen in der Datei
https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Daten/Fallzahlen_Kum_Tab.xlsx?__blob=publicationFile <https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Daten/Fallzahlen_Kum_Tab.xlsx?__blob=publicationFile> 
Des Weiteren nutzen wir momentan auch
https://npgeo-corona-npgeo-de.hub.arcgis.com/datasets/c2f3c3b935a242169c6bec82e1fa573e_0/about <https://npgeo-corona-npgeo-de.hub.arcgis.com/datasets/c2f3c3b935a242169c6bec82e1fa573e_0/about> 
https://npgeo-corona-npgeo-de.hub.arcgis.com/datasets/917fc37a709542548cc3be077a786c17_0/about <https://npgeo-corona-npgeo-de.hub.arcgis.com/datasets/917fc37a709542548cc3be077a786c17_0/about> 
(bei den letztgenannten Links bin ich mir gar nicht sicher, ob Sie da der richtige Ansprechpartner wären).

Für Ihre Hilfe danke ich Ihnen im Voraus,

mit freundlichen Grüßen
Martin Wiesenfeldt
