### ISSUE TITLE
Catch für RKI-Schnittstelle

### ISSUE THREAD

**Issue by wulffant** [highmed/SmICSCore#47]
Einbauen eines Hinweis, falls das Laden der RKI-Daten aufgrund sich geänderter Schnittstellen nicht funktioniert. 
Aktuell wird lediglich das Ladeicon angezeigt und der Benutzer wartet "endlos".

**Comment by wulffant** [comment]
Es sollte an den Standorten nachgefragt werden, ob ein Zugriff auf das Internet/die öffentliche Schnittstelle des RKI möglich ist oder das SmICS in einer Intranet-Umgebung ohne solche Zugriffsmöglichkeiten nach außen aufgesetzt wird. @Martin-Wiesenfeldt und Sylvia ergänzen diese Abfrage in der RollOut Checkliste.

**Comment by yussefal** [comment]
**Stand**: Funktion ist eingebaut
**TODO**: Es muss noch getestet werden

**Comment by yussefal** [comment]
Die Funktion wurde bearbeitet, daher muss ich mit @biermapa über den Testumfang sprechen.
