### ISSUE TITLE
Startseite "aufhübschen"

### ISSUE THREAD

**Issue by Martin-Wiesenfeldt** [highmed/SmICSCore#5]
Startseite (:9787) für Endbenutzer funktionell auf Stand bringen:

1.  Kurzer Introtext, wofür, 
2. minimale Bedienhinweise, 
3. Link zum Benutzerhandbuch
4. ordentliche Logo-Vorlagen einbinden

**Comment by wulffant** [comment]
Introtext und Bedienhinweise wurden eingefügt (23.04.)
Logo wurden eingefügt (26.04.)

**Comment by wulffant** [comment]
Satz einfügen: Hier (Link: https://github.com/highmed/SmICSCore/blob/develop/Benutzerhandbuch_CoSurvSmICS_V0_8_Test.pdf) finden Sie ein ausführliches Benutzerhandbuch.

**Comment by biermapa** [comment]
Done!

**Comment by wulffant** [comment]
Das HiGHmed-Auge-Bild soll noch entfernt werden. @Martin-Wiesenfeldt kannst du hier bitte nochmal deine Bildvorschläge einfügen?

**Comment by Martin-Wiesenfeldt** [comment]
Zwei Alternativvorschläge sind
https://pixabay.com/de/photos/coronavirus-virus-maske-corona-4914026/
https://cdn.pixabay.com/photo/2020/03/17/04/19/corona-4938929_960_720.jpg

**Comment by wulffant** [comment]
quick fix: öffentlich verfügbares Bild als Alternative einfügen

**Comment by Martin-Wiesenfeldt** [comment]
Weitere Vorschläge seitens unserer Design-Expertin:
-	Kontaktinformationen im Footer ergänzen
-	Links prüfen
-	Links hinter den Logos hinterlegen, die zu den jeweiligen Projektseiten führen
-	ggf. eine Logo für das SMICS entwickeln
-	alles Logos auf das gleiche Format bringen und in den Footer verschieben
-	BMBF-Logo erweitern um „gefördert vom“

**Comment by wulffant** [comment]
Vorschläge verschoben in neues Design-Issue für V1.0 (wie Freitag besprochen) #18
