### ISSUE TITLE
Datenschnittstelle und Ausgestaltung "Detaillierte Patientenansicht"

### ISSUE THREAD

**Issue by wulffant** [highmed/SmICSCore#50]
mit Symptome, Impfungen (ehem. "Christophs Modul")

**Comment by yussefal** [comment]
Für die Weiterentwicklung wird ein Termin mit @Kuri99 und @Lamachuk stattfinden.

**Comment by wulffant** [comment]
Symptome, Impfungen Testdaten wurden Tom zur Verfügung gestellt

**Comment by yussefal** [comment]
Der Termin mit @Kuri99, @Lamachuk, Felix und mir findet am 02.07.2021 statt.

**Comment by yussefal** [comment]
Für die Weiterentwicklung wurde ein neuen Branch erstellt. Felix und @yussefal übernehmen die Weiterentwicklung des Modules und der nächsten Termin findet am 08.07.2021 statt.

**Comment by yussefal** [comment]
Folgende Testdaten müssen für Felix noch zur Verfügung gestellt:
- [x] Impfstatus mit Covid Impfungen.
- [x] Labordaten mit Viruslast

**Comment by wulffant** [comment]
@wulffant 

- [x] Prüfen der Value Sets in GECCO bzgl COVID-Impfungen
- [x] Anpassen der Modelle? Absprechen mit Sarah
- [x] Viruslast Größenbereiche raussuchen

**Comment by Kuri99** [comment]
Impftestdaten sind mit Covid Impfungen erstellt und in der Testdomäne zu finden.

**Comment by yussefal** [comment]
Die erstellten Testdaten wurden an das Visiualisierungsteam weitergeleitet. Es fehlen nur noch Labordaten mit verschiedene Viruslast Werte. Außerdem ist noch die Frage, ob die Vektorimpfstoffe zusätzlich ein weiters Merkmal haben?

**Comment by wulffant** [comment]
- Informationen über Bereich der Viruslast weiteregegeben (Wertebereich: 0 bis 40)
- Keine Informationen über den Hersteller im Modell (auch nicht in GECCO) vorhanden -> zunächst die Bewertung der vollen Immunität nicht aufnehmen, tbd mit Domänenexperten in nächsten Evaluierungsrunden

**Comment by Kuri99** [comment]
Neue Patienten angelegt mit Labordaten und Viruslast. In der Testdomäne verfügbar.

**Comment by wulffant** [comment]
Testdaten an Felix weitergeleitet, offene Fragen geklärt. Stand der Umsetzung unklar, Termin mit Felix/Tom.

**Comment by yussefal** [comment]
Termin mit dem Visualisierung-Team fand am 04.08 statt. Es werden weitere Testdaten(Symptome und Impfstatus) benötigt und die InfectionSituation Schnittstelle muss noch bearbeitet werden.

**Comment by yussefal** [comment]
Die neuen Testdaten sowie die neue Implementierung der InfectionSituation Schnittstelle wurde dem Visualisierung-Team am 10.08 zur Verfügung gestellt.

**Comment by wulffant** [comment]
@wulffant  erfragt den aktuellen Stand

**Comment by wulffant** [comment]
Felix hat sich zurückgemeldet, dass sie mit den Testdaten arbeiten können. 
Alan erfragt nochmal, ob er bei der Visualisierung unterstützen kann und wie es lokal aufgesetzt werden kann.

**Comment by yussefal** [comment]
Meeting mit Tom und Felix fand am 05.10. statt. Tom und Felix setzen sich erstmal zusammen und werden dann alles umsetzen. Tom gibt uns spätestens Ende nächste Woche eine Rückmeldung.

**Comment by yussefal** [comment]
Tom hat mehrere branches zusammen gemerged unter anderem das Patientenansicht Modul. Er ist dabei das Modul ordentlich zu machen, es wird ähnlich dem Linelist sein.

**Comment by wulffant** [comment]
Übergabe an Kristina (Urlaub)
