### ISSUE TITLE
Buttons funktionell machen

### ISSUE THREAD

**Issue by Martin-Wiesenfeldt** [highmed/SmICSCore#6]
Querlinks funktionell machen
Auswahl der Patienten für Benutzer machbar; aus drop-down-Liste, oder Text, oder Handbuch/Datei/...

**Comment by wulffant** [comment]
@Martin-Wiesenfeldt please create a new issue for the second aspect because this is a different topic

**Comment by biermapa** [comment]
1. Punkt Done.
2. Punkt bitte in Freitagsrunde ansprechen, bevor Designvorschläge als Issues angelegt werden!
