### ISSUE TITLE
Ort für Dateienablage

### ISSUE THREAD

**Issue by wulffant** [highmed/SmICSCore#62]

**Comment by wulffant** [comment]
Sylvia macht Liste der aktuell verfügbaren Ordner

**Comment by sylvializmirandah** [comment]
E-Mail with link to shared GWDG ownCloud folder WP3.7 (Co-Surv-SmICS development) & WP3.9 (Co-Surv-SmICS Rollout) sent to Antje Wulff on June 23rd. Does this suffice? 

Are there any other ideas/suggestions to exchange information and streamline file sharing in the context of the Co-Surv-SmICS project? e.g. GitLab (used in Göttingen)?

**Comment by wulffant** [comment]
Neue Struktur vorgeschlagen, Antje gibt Feedback

**Comment by wulffant** [comment]
1.	Intern - Zugriff auf den gesamten B-FAST Ordner „Co-Surv-SmICS“ ausschließlich durch das SmICS Entwicklungsteam und das B-FAST Projektmanagement Team: https://owncloud.gwdg.de/index.php/s/4EwxhTkt0eATTmR   Kennwort: AUF ANFRAGE

2.	Öffentlich - Zugriff auf den B-FAST Ordner „Co-Surv-SmICS Öffentlich“ für B-FAST Kooperationspartner (Informationen werden bereitgestellt, um die Software lokal implementieren zu können): 
https://owncloud.gwdg.de/index.php/s/jGBovkfZc7cPKE4       Kennwort: AUF ANFRAGE

Folgende Dokumente sollten laut unserer Data Governance nicht frei zur Verfügung gestellt werden:
•	Dokumententwürfe, da diese ggf. noch zu ändernde Informationen enthalten. 
•	Arbeitsdokumente, da hier auch kritische Punkte frei besprochen werden können müssen.
•	Protokolle von Besprechungen, falls diese personenbezogene Zitate enthalten.
