### ISSUE TITLE
Einarbeitung der Punkte aus Benutzerhandbuch-Anmerkung von Antje

### ISSUE THREAD

**Issue by wulffant** [highmed/SmICSCore#65]

**Comment by wulffant** [comment]
Keine hohe Prio, erst nach Tests und Server

**Comment by yussefal** [comment]
Das Benutzerhandbuch wurde aktualisiert bzw. um die neuen Informationen ergänzt und dann an @wulffant weitergeleitet.

**Comment by yussefal** [comment]
Ich und @sylvializmirandah sind auf die aktualisierten Punkte eingegangen. Termin mit @wulffant ist notwendig!

**Comment by sylvializmirandah** [comment]
@sylvializmirandah hat die Kommentare und die neuen Screenshots eingearbeitet und die überarbeitete Version des Benutzerhandbuchs V0.8 (Test) an Antje und Alan zur Durchsicht geschickt.

**Comment by wulffant** [comment]
@yussefal bearbeitet Kommentare und schickt an @wulffant zur finalen Durchsicht.
