### ISSUE TITLE
Regelmäßige Statusupdates an die Standorte

### ISSUE THREAD

**Issue by wulffant** [highmed/SmICSCore#66]

**Comment by wulffant** [comment]
next: Anfang August, nach V0.9 Release
vorher -> Absprache mit @biermapa @wulffant

**Comment by wulffant** [comment]
Monatliches Update kommt Anfang August (vor V0.9 Release)

**Comment by sylvializmirandah** [comment]
Co-Surv-SmICS Newsletter (August 2021) wurde am 13.08. an alle B-FAST Projektpartner verschickt.

Inhalte:
- Verzögerung der Veröffentlichung von Co-Surv-SmICS V0.9 (ca. 1 Monat nach dem erwarteten Release)
- Aufforderung an die Standorte, uns über Probleme beim Testen zu informieren   
- Skizze der zugrundeliegenden Architektur des Co-Surv-SmICS
- Informationen zur Installation je nach Datenformat
- Ausblick: Verfeinerungen der Oberfläche und Anpassungen im nächsten Release, Ressourcendatenbank und für alle nutzbare Austauschplattform wird erstellt, Tests in Göttingen und Hannover mit pseudonymisierten Realdaten, erste Tests mit der auf FHIR basierenden Strecke in Göttingen, nächster Newsletter kommt in den nächsten zwei bis drei Wochen.
