### ISSUE TITLE
Konfig-Seite für RKI-R-Algorithmus

### ISSUE THREAD

**Issue by wulffant** [highmed/SmICSCore#68]
Abgeleitet aus den letzten Punkten im Issue #36  und ergänzend:

Erstellung einer Razor-Konfigurationsseite mit Auswahlmöglichkeiten

- [x] eines von 5 Erregern + 1 SARS COV 2 aus dem Antrag,
- [x] des Lookback-Zeitraums (aus welchem zurückliegenden Zeitraum sollen die Daten für den Algorithmus verwendet werden),
- [x] Startuhrzeit für tägliche Auswertung des Algorithmus,
- [x] Angabe der Station (od Klinik), für die der Algorithmus verwendet werden soll
- [x] Info Text

**Comment by wulffant** [comment]
Antje muss Termin vereinbaren (Tom, Pascal, Kristina, Paul, Antje)

**Comment by wulffant** [comment]
@Kuri99  Bild einfügen

**Comment by wulffant** [comment]
Kristina entwirft Konfig-Seite, aktuell: Hinzufügen/Löschen der Felder einfügen & Recherche zu geeigneten DB (NoSQL etc.)

**Comment by Kuri99** [comment]
![grafik](https://user-images.githubusercontent.com/80675221/126493082-0c2953c1-2b01-42e8-ab81-df672778a63e.png)

**Comment by wulffant** [comment]
@PaulWaldstein Ergebnisse des RKI Algorithmus (basierend auf den eingetellten Regeln) in JSON zwischenspeichern (for faster retrieval of visualisation)
-> dann: @Kuri99 Lösung für DB

**Comment by wulffant** [comment]
@wulffant Info-Text für Konfig-Seite erstellen (mit Warnhinweis bzgl 1-3 Wocheineinstellung)

**Comment by wulffant** [comment]
Überschrift: Konfigurationen zur Erkennung von Erregerhäufungen

Text: Basierend auf den vorliegenden, vergangenen Erregerbefunden im Klinikum ist das SmICS in der Lage, Ihnen einen Hinweis darauf zu geben, ob zu einem bestimmten Zeitpunkt mehr positive Erregerbefunde als üblich vorliegen ("Erregerhäufung"). In diesem Konfigurationsbereich haben Sie die Möglichkeit, verschiedene Regeln zu definieren, nach denen der statistische Algorithmus arbeiten soll. 

Eine Regel besteht immer aus (1) der Wahl einer Station (oder aller Stationen), (2) der Wahl eines Erregers (zur Auswahl stehen Ihnen aktuell 6 Erreger), (3) der Wahl eines "Look Back"-Zeitraumes (diese Variable bestimmt, welcher Umfang an vergangenen Daten mit in die Berechnung einbezogen werden soll, z.B. die letzten 1-12 Wochen), und (4) der Wahl, ob diese Regel zusätzlich einmalig retrospektiv - d.h. auf den gesamten Datenbestand - ausgeführt werden soll (die Standardeinstellung ist hier "Nein", d. h. die Regel wird nur auf die aktuellen Datenbestände bis zum in (3) definierten Zeitraum angewendet). 
Die von Ihnen angelegten Regeln werden täglich durchlaufen und die Ergebnisse neu berechnet. Dazu müssen Sie unter "Tgl. Ausführzeit der Regeln" eine Uhrzeit angeben, zu der die Berechnung stattfinden soll. 

Alle Regeln stehen Ihnen in der Visualisierung zur "Epidemiologischen Kurve" zur Auswahl zur Verfügung. Je nach Auswahl wird Ihnen dann dort die vom Algorithmus berechnete Entwicklung und Einschätzung dargestellt. 

Bitte beachten Sie: Die retrospektive Auswertung (4) ist ein sehr zeit- und rechenintensiver Prozess, der nur im Ausnahmefall oder zu Analysenzwecken gewählt werden sollte.

**Comment by Kuri99** [comment]
![grafik](https://user-images.githubusercontent.com/80675221/129745204-a29b6860-c4af-434d-93af-3b7c97944982.png)

**Comment by Kuri99** [comment]
- [x] Stationsanzeige bug fixen
- [x] tgl. Ausführungszeit abspeichern
- [x] KeimID über eigene Factory ergänzen

**Comment by Kuri99** [comment]
Config für das Zusammenführen mit dem Algorithmus fertiggestellt. Bugs und Fehler bitte melden.

- [ ] Tests anfertigen.
- [ ] User Ansichten trennen
- [ ] DB Anbindung

**Comment by PaulWaldstein** [comment]
- [x] Schleife über eine Prototypeingabedatei mit Sequenz von Parameterdatensätzen mit Speicherung der RKI-Algorithmus-Ergebnisse in die Outputdatei
- [x] Testen mit Beispieldaten aus der RKI_COVID19.csv-Datei
- [x] Einbindung des Algorithmus in den feature/Config-Branch mit der Konfig-Seite

- [x] Berücksichtigung der Sonderfälle von Regiestrierung von Befunden und Bewegungsdaten zur selben Zeit / Schleife über Sequenz mit Parametern unter Verwendung von Daten aus AQL-Abfragen
- [x] Cron-Job für Ausführungszeit aus der Konfig-Seite
- [x] Look Back Zeit Bug: Anfrage an Ann Christin Vietor - Umgang mit zu geringer Look Back Zeit im Algorithmus (< 4 Wochen Look Back -> NULL Werte) 
- [x] in Bezug auf Look Back Zeit Bug: Fehler/Hinweismeldung bei Auswahl 1-3 Wochen Look Back

**Comment by Kuri99** [comment]
- [x] Erregerstatus: mikrobiologisch/virologisch in ConfigFile und Model
- [x] Warnhinweis bei Look Back unter 4 Wochen
- [x] Zeitpunkt integrieren
- [x] Mikrobilogische Erreger disablen

**Comment by Kuri99** [comment]
Config wurde an den Algorhythmus angebunden. 
DB Anbindung ersteinmal zurückgestellt.
Auth für Useransichten integrieren steht noch aus.
