### ISSUE TITLE
Subdomain einrichten: bfast.num.umg.eu

### ISSUE THREAD

**Issue by Martin-Wiesenfeldt** [highmed/SmICSCore#7]

**Comment by wulffant** [comment]
Ggf. Zhu informieren, dass Alan und Paul bei Installation der Demo Version dabei sein möchten. @ZhuYufei990

**Comment by Martin-Wiesenfeldt** [comment]
Sehr geehrte(r) Martin Wiesenfeldt,

Ihre virtuelle Maschine mit dem Namen 'UKEI_smicspublic' wurde eingerichtet. 
Zur Installation müssen Sie sich per Remote Desktop Verbindung (RDP) auf unserem Windows-Terminalserver[2] einloggen und dort im Browser https://vcenter.gwdg.de aufrufen.
Bitte beachten Sie die veränderten Zugriffswege zum Terminalserver! [3] Bitte installieren Sie nach der Betriebssysteminstallation die VMware Tools[4].

Sollten Sie noch Fragen haben, wenden Sie sich bitte an support@gwdg.de.

--- Daten der VM ---
IP-Adresse: 134.76.17.89  (Die IP-Adresse wird per DHCP vergeben)
Betriebssystem: Ubuntu 20.04 LTS 64 Bit
Administrator: GWDG\wiesenfeldt3;GWDG\zhu13;GWDG\yussefalhaji;GWDG\waldstein1;GWDG\weber141
Kontaktperson: Martin Wiesenfeldt
E-Mail: yufei.zhu@med.uni-goettingen.de,martin.wiesenfeldt@med.uni-goettingen.de,alan.yussefalhaji@med.uni-goettingen.de,paul.waldstein@med.uni-goettingen.de,linus.weber@med.uni-goettingen.de
Institut: UKEI
Beschreibung: 

RDP und SSH sind aus dem GOENET freigeschaltet.
HTTP und HTTPS sind weltweit freigeschaltet.

@Hostmaster: Bitte folgende Firewall-Regeln setzen.
Firewall-Regeln: Erreichbar unter bfast.num.umg.eu


[1] https://vcenter.gwdg.de
[2] gwd-wints1.top.gwdg.de
[3] https://info.gwdg.de/docs/doku.php?id=en:services:server_services:compute_server:windows_terminal_server
[4] https://info.gwdg.de/dokuwiki/doku.php?id=de:services:server_services:virtual_server:start

Mit freundlichen Grüßen

Ihre GWDG
