### ISSUE TITLE
Timeout bei "Fallzahlen in der Region"

### ISSUE THREAD

**Issue by Martin-Wiesenfeldt** [highmed/SmICSCore#71]
Seit gestern (12.07.) bemerkt: Fallzahlen in der Region lieferte gestern nach langem Timeout eine ASPNET-Fehlermeldung, heute (13.07.) gar nichts mehr Fallzahlen in Deutschland geht jedoch.

**Comment by Martin-Wiesenfeldt** [comment]
Jetzt kam doch noch die Meldung:
Error.
An error occurred while processing your request.
Development Mode
Swapping to Development environment will display more detailed information about the error that occurred.

The Development environment shouldn't be enabled for deployed applications. It can result in displaying sensitive information from exceptions to end users. For local debugging, enable the Development environment by setting the ASPNETCORE_ENVIRONMENT environment variable to Development and restarting the app.

**Comment by yussefal** [comment]
Aufgrund auf einer Änderung der Datenquelle, müssen die Daten von GitHub bezogen werden, da das RKI die benötigten Daten jetzt auf Github Veröffentlicht.

Die Datenquelle wurde angepasst und der Fehler wurde behoben!
