### ISSUE TITLE
Vertretungstabelle (Personal)

### ISSUE THREAD

**Issue by wulffant** [highmed/SmICSCore#72]

**Comment by sylvializmirandah** [comment]
Eine Vertretungstabelle wurde erstellt und im internen Co-Surv-SmICS Ordner abgelegt: Co-Surv-SmICS > Intern > AP3.7 SmICS Entwicklung > Dokumente > Personalmanagement                                                                                                                        
Bitte tragt eure Urlaube & Absenzen, Aufgaben, notwendige Fachkenntnisse & Zugänge sowie Vertretungspersonen bei Abwesenheit hier ein.
