### ISSUE TITLE
SmICS V0.8 Test Cologne with Better: ThinkEHR expects CTX/ tags while processing compositions

### ISSUE THREAD

**Issue by sylvializmirandah** [highmed/SmICSCore#83]
Abdul Mateen from the University of Cologne tested the Co-Surv-SmICS Software V0.8 about 2-3 months ago. His findings were that the SmICS configuration seems more focused on EHRbase.

Issue encountered with the Better platform: Abdul Mateen was not able to upload the data set (zip file) provided in GitHub to Cologne's own repository with Better. To resolve the issue he generated their own synthetic data based on the SmICS templates to populate their internal repository. 

The following screenshot provided by Mateen shows that ThinkEHR expects CTX/ tags while processing compositions:  

![SmICS_Bad_Request_Köln](https://user-images.githubusercontent.com/82020896/137301491-3a10822b-6761-4f57-be83-5a6f023fae16.jpg)

**Comment by sylvializmirandah** [comment]
The following reponse from head developer Pascal Biermann was submitted to openEHR technicians in Cologne: 

Better offers two REST APIs: the Better REST API, known as REST API, and a more standardized REST API called openEHR REST API. Whether this solves the ctx/language problem outlined above, remains to be seen. Feedback from Cologne will be requested.

**Comment by Kuri99** [comment]
Issue fixed. New file will be send.
