### ISSUE TITLE
SmICS V0.9.1 Test Cologne with Better: Unavailability of Certain Terms

### ISSUE THREAD

**Issue by sylvializmirandah** [highmed/SmICSCore#84]
Cologne did further software testing using the template and data available in the latest Co-Surv-SmICS version 0.9.1 with the OpenEHR rest API (instead of Better REST API previously used). The Postman collection seems to work. However, they encountered some issues relating to unavailability of certain terms, notably "Impfstoff". Please see the following screenshots:

![Smics_Error_Pt4](https://user-images.githubusercontent.com/82020896/138241115-e69422b4-507e-4e3f-ae4a-9a404367209a.JPG)

![Smics_Error_Pt6](https://user-images.githubusercontent.com/82020896/138241130-583a5499-7c63-47d6-a279-cab98e80453a.JPG)

![Smics_Error_Pt8](https://user-images.githubusercontent.com/82020896/138241143-e1899520-039f-4c16-b55e-c3a11cb68fa5.JPG)

![Smics_Error_Pt14](https://user-images.githubusercontent.com/82020896/138241160-8fb94598-10b6-434b-9ae1-2bc6c6181133.JPG)

![Smics_Error_Pt15](https://user-images.githubusercontent.com/82020896/138241181-36828879-ad8c-4aba-b845-ddc93630a326.JPG)

![Smics_Error_Pt16](https://user-images.githubusercontent.com/82020896/138241197-3174db86-b0c8-41ef-a00f-c9279c27bc87.JPG)

![Smics_Error_Pt27](https://user-images.githubusercontent.com/82020896/138241212-fe71c016-ebfd-47e1-bd29-439cbec1528d.JPG)

**Comment by Kuri99** [comment]
already fixed for new version 1.0 and a file has been send to martin.

**Comment by sylvializmirandah** [comment]
To access the revised Postman collection prior to the release of V1.0 please contact: medinf.bfast@med.uni-goettingen.de
