### ISSUE TITLE
SmICS V0.9.1 Test Cologne with Better: Failure to Retrieve Data using AQL Queries in Better Studio

### ISSUE THREAD

**Issue by sylvializmirandah** [highmed/SmICSCore#85]
The team in Cologne tried to use the AQL queries (available in Postman collection) in Better Studio but were not able to retrieve any data. The reason for this may be that their Better is configured to Better REST API and not OpenEHR REST API thus no data is retrieved. They will look into this further and send feedback.  

![AQL_PatientWards_Ouput_Studio](https://user-images.githubusercontent.com/82020896/138243105-773fac40-1d0a-4a99-871e-7a522cca16c6.JPG)

**Comment by Kuri99** [comment]
'ehrID' should be filled with an actual ID, 'endtime' and 'starttime' should be filled with a date to get results.
Example:
SELECT....and e/ehr_id/value ='519dea3894..' and m/data[at0001]/items[at0004]/value/value <= '2021-02-02' and .... >='2021-02-01'....
