### ISSUE TITLE
Disclaimer: minimal hardware requirements for usage (screen resolution)

### ISSUE THREAD

**Issue by Martin-Wiesenfeldt** [highmed/SmICSCore#9]
I don't know whether it can be realized in this short time. But it would be best if the window opens without any warning if the requirements are met and can not be resized below this minimum. And only in case the requirements are missed the warning appears.

**Comment by wulffant** [comment]
needs more description, to be discussed in next Friday round. @Martin-Wiesenfeldt please add this to your points for Friday

**Comment by wulffant** [comment]
-> für Version 1.0 Oktober
Martin informiert Standorte bei Auslieferung der Demo-Version und erfragt need, ggf. für Tablet-Ansicht.

**Comment by wulffant** [comment]
Antje nimmt diesen Punkt zusätzlich als Diskussionspunkt für das nächste Tandem-Meeting (HiGHmed IC) auf

**Comment by wulffant** [comment]
Requirements are documented in Benutzerhandbuch, warnings may be part of any future versions.
